### PR TITLE
🔧FF: adding mexican spanish to v4

### PR DESCRIPTION
**Pull request by HarryMatthey**

### CODE REVIEW

**Comment by HarryMatthey** [comment]
@lacazeto is this the right way to add it?

**Comment by lacazeto** [comment]
@HarryMatthey no, the plugin won't accept `lang=[locale-lang]` syntaxes. It is only valid `lang=[lang]`

Farfetch hosted page works around that by adding some custom js that parses that for the plugin. You had already done that before https://github.com/parcelLab/farfetch.delivery-status.com/pull/23/files, despite not being needed as mx is already defined in there as per my comment in that PR.

**Comment by HarryMatthey** [comment]
I think it got it thanks! Made a change to the tracking link and that should fix it, thanks for your patience!

**Comment by lacazeto** [comment]
> I think it got it thanks! Made a change to the tracking link and that should fix it, thanks for your patience!

The only think I noticed missing was this translation https://github.com/parcelLab/farfetch.delivery-status.com/blob/master/src/js/parcellab-farfetch.js#L169

But the rest should be fine!

**Pull request closed without merging**
