### PR TITLE
🔧 FF: Adding arabic language

### PR DESCRIPTION
**Pull request by HarryMatthey**

### CODE REVIEW

**Comment by HarryMatthey** [comment]
@thomas-lalicata-pl @jkrenge not sure if this is all that is needed in this repo to enable Arabic on the FarFetch tracking page?

**Comment by lacazeto** [comment]
Hi @HarryMatthey , do we want to officially start supporting the Arabic language or would this be something specific for FarFetch (https://github.com/parcelLab/farfetch.delivery-status.com/pull/20#event-7750910071)?

Because it is not that simple... apart from updating the translations in here, we also need to enable them in the backend ([example](https://github.com/parcelLab/Backend/pull/17687/files)), update the language switcher for our self hosted pages ([here](https://github.com/parcelLab/Versand-Status.de/blob/2947d3af12fa6934cc0f312b3e2e23f9aaed7157/src/js/lang-switcher.js)), update plugin V5 and also the official public documentation.

I would recommend to open a ticket for us to help with that (we can provide a spreadsheet with all the required translations), but please let us know if you prefer to do it some other way!

**Comment by HarryMatthey** [comment]
Hey @lacazeto this is specifically for FarFetch, I wasn't sure what exactly was needed so if you can let me know then I'll get it all from them for you 🙂

**Comment by lacazeto** [comment]
> Hey @lacazeto this is specifically for FarFetch, I wasn't sure what exactly was needed so if you can let me know then I'll get it all from them for you 🙂

In that case, you should be able to move the changes from here and include in your PR https://github.com/parcelLab/farfetch.delivery-status.com/pull/20/files.
You can create a `customTranslations` entry in your new code there and copy paste the changes there. 

The country names are not necessary to go there as they don't have a different translation.

For fully enabling the language, we need to also update translations coming from the backend. You can refer to that PR that guirec created and I posted above (adding greek lang support). The necessary values are presented in this spreadsheet https://parcellab-my.sharepoint.com/:x:/p/amy/EWhgXXPWqOFOgiYkKt-NU80Be6EsCjLN_clqgpcBkem1Ig?e=gxlbHf, but I'm afraid you'll have to refer directly to the backend's repository code to see the original english texts!

**Comment by HarryMatthey** [comment]
Thanks @lacazeto!
I did try that but for some reason when I tested locally the customTranslations didn't pull through, I added them to that PR [here](https://github.com/parcelLab/farfetch.delivery-status.com/pull/20) maybe you can tell me where I went wrong?
http://localhost:3000/src/?locale=om-ar&orderNo=NB2T5X&lang=ar&show_articleList=yes&s=UBRRJnCAen&oxm_em=parcelLab

**Comment by lacazeto** [comment]
> Thanks @lacazeto! I did try that but for some reason when I tested locally the customTranslations didn't pull through, I added them to that PR [here](https://github.com/parcelLab/farfetch.delivery-status.com/pull/20) maybe you can tell me where I went wrong? http://localhost:3000/src/?locale=om-ar&orderNo=NB2T5X&lang=ar&show_articleList=yes&s=UBRRJnCAen&oxm_em=parcelLab

Sorry about that... we need to enable this for the V4 of the plugin, which is used only by farfetch. So I created a PR in [here](https://github.com/parcelLab/parcelLab-js-plugin/pull/103) with your changes and I can deploy after merged.

**Comment by lacazeto** [comment]
I already deployed, so this PR is no longer needed!
And for the farfetch one, you shouldn't need the additional `customTranslations` changes I asked you to include as these were directly added to the plugin V4.

**Pull request closed without merging**
