### PR TITLE
🔧 FF: Changes to tracking page wording

### PR DESCRIPTION
**Pull request by HarryMatthey**
FF requested changes to the wording on the tracking page for Dutch, Spanish and Italian.

### CODE REVIEW

**Comment by HarryMatthey** [comment]
@jkrenge does this work/is this ok?

**Comment by jkrenge** [comment]
I think @parcelLab/b2c will migrate that to v5 anyways, and then we'll have different wording again, so maybe rather as a custom hook function? Or how would we make sure this change stays for FF?

**Comment by lacazeto** [comment]
As far as I'm aware, farfetch is the only one using this version of the plugin and it is packing such an amount of custom stuff that we still don't have plans to migrate it to V5. 

But since we host FF, we can also pass custom translations during the plugin's initialisation. That would be another option!

**Comment by jkrenge** [comment]
Resolved by https://github.com/parcelLab/farfetch.delivery-status.com/pull/18

**Pull request closed without merging**
